# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 08:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('wifi', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:\\,(-)?\\d+)*\\Z'), code='invalid', message='Integer Comma Error')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
