# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myspyapi', '0002_auto_20180202_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
