# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspyapi', '0005_locationdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdata',
            name='userhandle',
        ),
    ]
