# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspyapi', '0009_locationdata_userhandle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationdata',
            table='Locationdata',
        ),
    ]
