"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(@y0wa@d*9o(yt6s!6^n2!*eub*53hs3jmja%i8by9wvs2ahi3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.17.%s.%s' %(i,j) for i in range(256) for j in range (256)]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myspyapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# if DEBUG:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'sql_server.pyodbc',
#             'NAME': 'mysqldatabase43349',
#             'USER': 'mysqldbuser',
#             'PASSWORD': 'myspy@mat14',
#             'HOST': 'myspy-mysqldbserver',
#             'PORT': '1433',
#             'OPTIONS': {
#                 'driver': 'FreeTDS',
#                 'host_is_server': True,
#             },
#         }
#     }
# else :
#     DATABASES = {
#         'default': {
#             'ENGINE': 'sql_server.pyodbc',
#             'NAME': os.getenv("DATABASE_NAME"),
#             'USER': os.getenv("DATABASE_USER"),
#             'PASSWORD': os.getenv("DATABASE_PASSWORD"),
#             'HOST': os.getenv("DATABASE_HOST"),
#             'PORT': os.getenv("DATABASE_PORT"),
#             'OPTIONS' : {
#                     'driver': 'ODBC Driver 13 for SQL Server',
#                     'MARS_Connection': 'True',
#                 }
#         }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'mysqldatabase43349',
#         'USER': 'mysqldbuser@myspy-mysqldbserver',
#         'PASSWORD': 'myspy@mat14',
#         'HOST': 'myspy-mysqldbserver.mysql.database.azure.com',
#         'PORT': '3306',
#         'OPTIONS': {
#             'driver': 'MySQL ODBC 5.3 UNICODE Driver',
#             'host_is_server': True,
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'



# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticatedOrReadOnly',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         #'rest_framework_jwt.authentication.JSONWebTokenAuthentication',

#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#     ),
# }

STATIC_URL = '/home/gaurav/cfd18/webapp/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')